version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      # a packaged system that has the instructions for creating a running container.
      - image: circleci/ruby:2.3.3

    # actions that need to be taken to perform your job
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:USaw9IC3qDmo5lTDeDE1ctu2VeLlrFbqhYZrPVJlw2U"

      # checks out the source code for a job over SSH
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run:
          name: install dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "source-design-merge" ]; then
               git config --global user.email "accounts@plot.ly"
               git config --global user.name "Deployer"
               rake deploy
            else
               bundle exec jekyll build
            fi
